pipeline {
    environment {
    registry = '430963847993.dkr.ecr.us-west-2.amazonaws.com/qt-practical-devops-ecr'
    registryCredential = 'aws-credentials'
    dockerImage = 'frontend'
    frontendTag = "frontend-$BUILD_NUMBER"
    }
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
         stage('Clone repository') { 
            steps { 
                script{
                checkout scm
                }
            }
        }
        stage('Build') { 
            steps {         
                script {
                    //dockerImage = docker.build registry + ":frontend-$BUILD_NUMBER"
                    app = docker.build(frontendTag, "-f src/frontend/Dockerfile .")
                }
            }
        }
        stage('Test'){
            steps {
                 echo 'Empty'
            }
        }
        stage('Deploy image') {
            steps {
                //sh "docker tag ${frontendTag} ${registry}:${frontendTag}"
                script{
                    docker.withRegistry("https://" + registry, "ecr:us-west-2:" + registryCredential) {
                     app.push("${frontendTag}")
                    }
                }
            }
        }
    }
}