pipeline {
    environment {
    registry = '430963847993.dkr.ecr.us-west-2.amazonaws.com/qt-practical-devops-ecr-frontend'
    registryCredential = 'aws-credentials'
    tag = "$BUILD_NUMBER"
    dockerImage = "frontend-${tag}"
    }

    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
         stage('Clone repository') { 
            steps { 
                script{
                checkout scm
                }
            }
        }
        stage('Build') { 
            steps {         
                script {
                    app = docker.build(dockerImage, "-f src/frontend/Dockerfile .")
                }
            }
        }
        stage('Trivy Scan')
        {
            steps {
                sh "trivy ${dockerImage}:latest"
            }
        }
        stage('Deploy image') {
            steps {
                script{
                    docker.withRegistry("https://" + registry, "ecr:us-west-2:" + registryCredential) {
                        sh "docker tag ${dockerImage} ${registry}:${tag}"
                        sh "docker push ${registry}:${tag}"
                    }
                }
                
            }
        }
    }
}